# Generated by Django 5.0 on 2024-03-15 06:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0001_initial'),
        ('department', '0002_department_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemodel',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department'),
        ),
    ]
