# Generated by Django 5.0 on 2024-03-15 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=50)),
                ('device_type', models.CharField(max_length=30)),
                ('identification_no', models.CharField(max_length=30)),
            ],
        ),
    ]
