# Generated by Django 5.0 on 2024-03-15 11:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Company', '0001_initial'),
        ('Employee', '0002_alter_employeemodel_department'),
        ('device', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('historyType', models.IntegerField(choices=[(1, 'Provide'), (2, 'Return')], null=True)),
                ('is_returned', models.BooleanField(default=False)),
                ('return_date', models.DateTimeField(blank=True, null=True)),
                ('provide_date', models.DateTimeField(auto_now_add=True)),
                ('account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Company.companymodel')),
                ('device', models.ManyToManyField(to='device.devicemodel')),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Employee.employeemodel')),
            ],
        ),
    ]
